# Generated by Django 3.2.8 on 2021-11-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attacker_cords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='villages_attacks', to='backend.village'),
        ),
        migrations.AlterField(
            model_name='report',
            name='attacker_cords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='villages_reports', to='backend.village'),
        ),
    ]
