# Generated by Django 3.2.8 on 2022-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
    ]
