# Generated by Django 3.1.4 on 2021-10-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attacker_name',
            field=models.CharField(max_length=99),
        ),
    ]
