# Generated by Django 3.1.4 on 2021-10-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_auto_20211029_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
