# Generated by Django 3.1.4 on 2021-04-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_booktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=None)),
                ('note', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_author', to='backend.author')),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_type', to='backend.booktype')),
            ],
        ),
    ]
