# Generated by Django 3.1.4 on 2021-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_villagedetailinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagedetailinformation',
            name='lose_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
