# Generated by Django 3.1.4 on 2021-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
