# Generated by Django 3.1.4 on 2021-10-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0003_villagedetailinformation_lose_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='attacker_x',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='attacker_y',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='defender_x',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='defender_y',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='send_time',
        ),
        migrations.AddField(
            model_name='attack',
            name='attacker_cords',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attack',
            name='defender_cords',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attack',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
