# Generated by Django 3.1.4 on 2021-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_book_date_of_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0, max_length=50)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
