# Generated by Django 3.1.4 on 2022-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0008_auto_20210402_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_of_publication',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
