# Generated by Django 3.1.4 on 2022-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0009_auto_20220330_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
