# Generated by Django 3.2.8 on 2022-01-10 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('skill_type', models.IntegerField(choices=[(1, 'Ziemia'), (2, 'Ogień'), (3, 'Woda'), (4, 'Wiatr')])),
                ('min_attack', models.IntegerField()),
                ('max_attack', models.IntegerField()),
                ('hit_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='in_work',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to=None)),
                ('skin', models.ImageField(upload_to=None)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('feeding', models.IntegerField()),
                ('in_team', models.BooleanField(default=False)),
                ('in_market', models.BooleanField(default=False)),
                ('in_travel', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'Ziemia'), (2, 'Ogień'), (3, 'Woda'), (4, 'Wiatr')])),
                ('strength_b', models.IntegerField()),
                ('strength_p', models.IntegerField()),
                ('strength_t', models.IntegerField()),
                ('intelligence_b', models.IntegerField()),
                ('intelligence_p', models.IntegerField()),
                ('intelligence_t', models.IntegerField()),
                ('VitalityB', models.IntegerField()),
                ('VitalityP', models.IntegerField()),
                ('VitalityT', models.IntegerField()),
                ('AgilityB', models.IntegerField()),
                ('AgilityP', models.IntegerField()),
                ('AgilityT', models.IntegerField()),
                ('KnowledgeB', models.IntegerField()),
                ('KnowledgeP', models.IntegerField()),
                ('KnowledgeT', models.IntegerField()),
                ('LuckB', models.IntegerField()),
                ('LuckP', models.IntegerField()),
                ('LuckT', models.IntegerField()),
                ('affection', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_0', to='accounts.monsterskill')),
                ('skill_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_1', to='accounts.monsterskill')),
                ('skill_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_2', to='accounts.monsterskill')),
                ('skill_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_3', to='accounts.monsterskill')),
                ('skill_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_4', to='accounts.monsterskill')),
            ],
        ),
    ]
